policyServer:
  scriptStore:
    type: file
    path: src/main/resources/scripts
  policyStore:
    type: file
    path: /tmp/home-policies
  configurationStore:
    type: file
    path: /tmp/home-config

logging:
  level: INFO

  loggers:
    "com.furnaghan": DEBUG
