policyServer:
  scriptStore:
    type: file
    path: src/main/resources/scripts
  policyStore:
    type: file
    path: src/main/resources/policies
  configurationStore:
    type: file
    path: src/main/resources/components

logging:
  level: INFO

  loggers:
    "com.furnaghan": DEBUG
